#!/usr/bin/env bash
set -euo pipefail

echo "============================================================"
echo "                   Trawl — Setup & Bringup                 "
echo "============================================================"
echo ""

# 1. Prerequisite check
echo "Checking prerequisites..."
if ! command -v docker &> /dev/null; then
    echo "ERROR: 'docker' command not found. Please install Docker first:"
    echo "       https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "ERROR: Docker daemon is not running. Please start Docker and try again."
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "ERROR: 'docker compose' (v2+) is required. Please update Docker Desktop or install the compose plugin."
    exit 1
fi

echo "✔ Docker environment verified."
echo ""

# 2. Interactive prompt for configuration
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

ENV_FILE="${ROOT_DIR}/.env"
CONFIG_FILE="${ROOT_DIR}/config/default.json"

if [ -f "${ENV_FILE}" ]; then
    read -rp ".env file already exists. Overwrite? (y/N): " OVERWRITE_ENV
    OVERWRITE_ENV="${OVERWRITE_ENV:-n}"
else
    OVERWRITE_ENV="y"
fi

if [[ "${OVERWRITE_ENV}" =~ ^[Yy]$ ]]; then
    read -rp "Enter Seed Domains (comma-separated, e.g. example.com): " SEED_DOMAINS_INPUT
    read -rp "Enter LLM API Key (OpenAI-compatible, or press Enter for local/none): " LLM_KEY_INPUT
    read -rp "Enter Alert Webhook URL (optional): " WEBHOOK_INPUT

    SEED_DOMAINS_INPUT="${SEED_DOMAINS_INPUT:-example.com}"

    cat <<EOF > "${ENV_FILE}"
# Generated by setup.sh on $(date)
LLM_API_KEY=${LLM_KEY_INPUT}
SEED_DOMAINS=${SEED_DOMAINS_INPUT}
WEBHOOK_URL=${WEBHOOK_INPUT}
CONVEX_URL=http://localhost:3210
EOF

    mkdir -p "${ROOT_DIR}/config"
    cat <<EOF > "${CONFIG_FILE}"
{
  "instanceName": "default",
  "seedDomains": [$(echo "${SEED_DOMAINS_INPUT}" | sed 's/,/", "/g' | sed 's/^/"/' | sed 's/$/"/')],
  "seedCidrs": [],
  "seedRepos": [],
  "webhookUrl": "${WEBHOOK_INPUT}",
  "staleAfterDays": 90,
  "triageThreshold": "high",
  "secretVerificationEnabled": true,
  "maxRepoCloneSizeMb": 500,
  "aiProvider": {
    "baseUrl": "https://api.openai.com/v1",
    "apiKey": "${LLM_KEY_INPUT}",
    "model": "gpt-4o",
    "timeoutMs": 30000
  }
}
EOF
    echo "✔ Created .env and config/default.json"
fi

echo ""
echo "Bringing up Trawl Docker Compose stack..."
cd "${ROOT_DIR}/deploy/compose"
docker compose up -d

echo ""
echo "============================================================"
echo "  Trawl is starting up!"
echo "  Dashboard URL: http://localhost:8080"
echo "  Convex Backend: http://localhost:3210"
echo "============================================================"
