[job-exec "daily-discovery-worker"]
schedule = 0 0 1 * * *
container = trawl-discovery-worker
command = /entrypoint.sh

[job-exec "daily-scan-worker"]
schedule = 0 0 2 * * *
container = trawl-scan-worker
command = /entrypoint.sh

[job-exec "daily-repo-scan-worker"]
schedule = 0 0 3 * * *
container = trawl-repo-scan-worker
command = /entrypoint.sh
