// Command specledger keeps openspec/STATUS.md honest about the change folders
// beside it, and fails the build when the two disagree.
//
// The spec tree is this project's central argument: say what you expect, then
// record what happened. An argument nobody audits decays, and it decays
// quietly — every failure this command checks for has already happened here at
// least once.
//
//   - Change 017 was archived with `git mv`, and an editor with an unsaved
//     buffer wrote its ledger back to the old path, leaving the change present
//     in two places at once. `ls openspec/changes` would have shown it. Nobody
//     ran `ls`.
//   - The same incident produced a zero-byte tasks.md while proposal.md went on
//     citing "Phase 1 of tasks.md". A ledger that asserts nothing reads, from
//     outside, exactly like one whose work is complete.
//   - STATUS.md carries per-change counts regenerated by a shell loop pasted at
//     the top of the file. Counts maintained by remembering to run something
//     are counts that are wrong.
//
// Like cmd/egressdoc, this runs in --check mode in CI and in write mode
// locally, so the committed document is verifiable rather than merely
// plausible.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	root := flag.String("root", "openspec", "the openspec tree to read")
	status := flag.String("status", filepath.Join("openspec", "STATUS.md"), "the status document to reconcile")
	check := flag.Bool("check", false, "report disagreement instead of correcting it")
	flag.Parse()

	ledgers, problems, err := scan(*root)
	if err != nil {
		fail(err)
	}
	problems = append(problems, validate(ledgers)...)

	existing, err := os.ReadFile(*status)
	if err != nil {
		fail(fmt.Errorf("reading %s: %w", *status, err))
	}

	updated, statusProblems := reconcile(string(existing), ledgers)
	problems = append(problems, statusProblems...)

	stale := updated != string(existing)

	// Structural problems are reported whether or not we are writing, because
	// none of them is something this command can correct. A change present in
	// two places has a right answer only its author knows.
	if len(problems) > 0 {
		for _, p := range problems {
			fmt.Fprintf(os.Stderr, "specledger: %s\n", p)
		}
		if stale && !*check {
			if err := os.WriteFile(*status, []byte(updated), 0o644); err != nil {
				fail(err)
			}
			fmt.Fprintf(os.Stderr, "specledger: counts in %s were corrected; the problems above were not\n", *status)
		}
		os.Exit(1)
	}

	if *check {
		if stale {
			fail(fmt.Errorf("%s disagrees with the ledgers beside it; run `go run ./cmd/specledger` and commit the result", *status))
		}
		fmt.Printf("specledger: %d ledgers, %s agrees with all of them\n", len(ledgers), *status)
		return
	}

	if stale {
		if err := os.WriteFile(*status, []byte(updated), 0o644); err != nil {
			fail(err)
		}
		fmt.Printf("specledger: updated %s\n", *status)
		return
	}
	fmt.Printf("specledger: %d ledgers, %s already agrees with all of them\n", len(ledgers), *status)
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "specledger: %v\n", err)
	os.Exit(1)
}
