// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {store} from '../models';
import {version} from '../models';

export function AssessDomain(arg1:string):Promise<service.DomainAssessment>;

export function EraseDiscoveredData():Promise<void>;

export function GetAssets(arg1:store.AssetStatus):Promise<Array<store.Asset>>;

export function GetDomainAssessment(arg1:string):Promise<service.DomainAssessment>;

export function GetDomainAssessments():Promise<Array<service.DomainAssessment>>;

export function GetEmailPostures():Promise<Array<store.EmailPosture>>;

export function GetFindings(arg1:string):Promise<Array<store.Finding>>;

export function GetRegressions():Promise<Array<store.Regression>>;

export function GetSecretFindings(arg1:string):Promise<Array<store.SecretFinding>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVersion():Promise<version.Info>;

export function RemoveAsset(arg1:string):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function ScanEmailPosture(arg1:string):Promise<store.EmailPosture>;

export function TriggerScan(arg1:string,arg2:string):Promise<void>;
