// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssets(arg1) {
  return window['go']['main']['App']['GetAssets'](arg1);
}

export function GetEmailPostures() {
  return window['go']['main']['App']['GetEmailPostures']();
}

export function GetFindings(arg1) {
  return window['go']['main']['App']['GetFindings'](arg1);
}

export function GetRegressions() {
  return window['go']['main']['App']['GetRegressions']();
}

export function GetSecretFindings(arg1) {
  return window['go']['main']['App']['GetSecretFindings'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function ScanEmailPosture(arg1) {
  return window['go']['main']['App']['ScanEmailPosture'](arg1);
}

export function TriggerScan(arg1, arg2) {
  return window['go']['main']['App']['TriggerScan'](arg1, arg2);
}
