package vantage

import (
	"fmt"
	"sort"
	"strings"

	vaudit "github.com/adedayo/vantage/pkg/audit"
)

// EgressDocumentation renders operator-facing documentation of what assessment
// contacts, derived from the checks' own declarations.
//
// Generating it is not a convenience. Hand-written egress documentation is a
// second statement of what the code does, maintained by whoever remembers, and
// it is wrong from the first upgrade that adds a check — at which point it is
// worse than nothing, because an operator has read it and believes it. Derived
// from the same profiles the policy gate and the transport use, it cannot say
// something different from what happens.
//
// The document is written against a policy so that it answers the question an
// operator actually has, which is not "what could this tool do" but "what will
// this deployment do, and what am I declining".
func EgressDocumentation(caps vaudit.Capabilities, policy EgressPolicy) (string, error) {
	sel, err := SelectChecks(caps, policy)
	if err != nil {
		return "", err
	}

	profiles := map[string]vaudit.EgressProfile{}
	summaries := map[string]string{}
	for _, c := range caps.Checks {
		profiles[c.Name] = c.Egress
		summaries[c.Name] = c.Summary
	}

	var b strings.Builder
	b.WriteString("# What Trawl contacts\n\n")
	b.WriteString("<!-- Generated by `go run ./cmd/egressdoc`. Do not edit by hand: this file is\n")
	b.WriteString("     derived from the egress profiles the checks themselves declare, so that it\n")
	b.WriteString("     cannot describe behaviour the code does not have. -->\n\n")

	b.WriteString("Every DNS and email assessment check states, as structured data, what it\n")
	b.WriteString("touches. This deployment's policy is expressed over those categories rather\n")
	b.WriteString("than over check names, so a check added in a future release is admitted only\n")
	b.WriteString("if everything it needs was already permitted. A check requiring anything else\n")
	b.WriteString("is withheld and recorded as `not_checked`, with the reason below - it does not\n")
	b.WriteString("run and then get reported, and it does not run quietly.\n\n")

	b.WriteString("## Categories of contact\n\n")
	b.WriteString("| Category | Meaning | Permitted here |\n|---|---|---|\n")
	for _, c := range EgressClasses() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", c, classMeaning(c), yesNo(policy.allows(c))))
	}

	b.WriteString("\n## Third-party services\n\n")
	b.WriteString("Consent is per service, not blanket. Permitting the `third-party` category\n")
	b.WriteString("alone grants nothing: a service added upstream is a new disclosure of your\n")
	b.WriteString("names to someone, and it waits for a decision.\n\n")
	b.WriteString("| Service | Endpoints | Consented here |\n|---|---|---|\n")
	for _, s := range vaudit.ThirdPartyServices() {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
			s, code(s.Endpoints()), yesNo(policy.consents(s))))
	}

	b.WriteString("\n## Checks that run\n\n")
	if len(sel.Checks) == 0 {
		b.WriteString("_None. This policy withholds every available check._\n")
	} else {
		b.WriteString("| Check | What it assesses | What it contacts |\n|---|---|---|\n")
		for _, name := range sel.Checks {
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
				name, orDash(summaries[name]), describe(profiles[name])))
		}
	}

	b.WriteString("\n## Checks withheld\n\n")
	if len(sel.Excluded) == 0 {
		b.WriteString("_None. This policy admits every available check._\n")
	} else {
		b.WriteString("Each of these is recorded against the asset as `not_checked` with the\n")
		b.WriteString("reason given, so a coverage figure never counts them as assessed.\n\n")
		b.WriteString("| Check | Why it is withheld |\n|---|---|\n")
		for _, e := range sel.Excluded {
			b.WriteString(fmt.Sprintf("| `%s` | %s |\n", e.CheckID, e.Reason))
		}
	}

	b.WriteString("\n## Hosts the transport will permit\n\n")
	b.WriteString("Besides the domains you have authorised, the assessment transport refuses\n")
	b.WriteString("every host not listed here. The list is derived from the checks that actually\n")
	b.WriteString("run, so consenting to a service whose checks are withheld opens nothing.\n\n")
	allow := sel.EndpointAllowlist()
	if len(allow) == 0 {
		b.WriteString("_None. Only names within your authorised domains are contacted._\n")
	} else {
		for _, h := range allow {
			b.WriteString(fmt.Sprintf("- `%s`\n", h))
		}
	}

	return b.String(), nil
}

func classMeaning(c EgressClass) string {
	switch c {
	case ClassResolver:
		return "Ordinary DNS queries through a recursive resolver."
	case ClassTargetNameservers:
		return "Queries sent straight to your domain's authoritative nameservers, which is visible to them in a way an ordinary query is not."
	case ClassTargetHTTPS:
		return "HTTPS requests to your own infrastructure, such as retrieving an MTA-STS policy file."
	case ClassThirdParty:
		return "Contact with a service that is neither yours nor the target's. Requires per-service consent as well."
	case ClassIntrusive:
		return "Contact beyond an ordinary query, such as requesting a zone transfer. Never destructive, but worth agreeing to."
	case ClassOffline:
		return "No network contact at all."
	default:
		return ""
	}
}

func describe(e vaudit.EgressProfile) string {
	var parts []string
	for _, c := range ClassesOf(e) {
		parts = append(parts, "`"+string(c)+"`")
	}
	for _, s := range e.ThirdParty {
		parts = append(parts, fmt.Sprintf("(%s)", s))
	}
	if len(parts) == 0 {
		return "_undeclared_"
	}
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}

func code(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}
