// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssets(arg1) {
  return window['go']['main']['App']['GetAssets'](arg1);
}

export function GetFindings(arg1) {
  return window['go']['main']['App']['GetFindings'](arg1);
}

export function GetRegressions() {
  return window['go']['main']['App']['GetRegressions']();
}

export function GetSecretFindings(arg1) {
  return window['go']['main']['App']['GetSecretFindings'](arg1);
}
