// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function GetAssets(arg1:store.AssetStatus):Promise<Array<store.Asset>>;

export function GetFindings(arg1:string):Promise<Array<store.Finding>>;

export function GetRegressions():Promise<Array<store.Regression>>;

export function GetSecretFindings(arg1:string):Promise<Array<store.SecretFinding>>;
