import { Injectable, signal } from '@angular/core';

// Declare Wails bindings (typically auto-generated by Wails CLI in wailsjs/go/main/App)
declare const window: any;

@Injectable({
  providedIn: 'root'
})
export class WailsIpcService {
  // UI State
  public theme = signal<'light' | 'dark'>('light');
  public activeTab = signal<'overview' | 'assets' | 'findings' | 'email' | 'secrets' | 'scope'>('overview');
  
  // Data State
  public assets = signal<any[]>([]);
  public findings = signal<any[]>([]);
  public emailPostures = signal<any[]>([]);
  public secretFindings = signal<any[]>([]);

  // Engine State
  public isScanning = signal<boolean>(false);
  public scanStatusMessage = signal<string>('');
  public lastScanDate = signal<string | null>(null);

  // Scope State
  public seedDomainsList = signal<string[]>([]);
  public seedCidrsList = signal<string[]>([]);
  public seedReposList = signal<string[]>([]);
  public isAuthorized = signal<boolean>(false);
  public signerName = signal<string>('');
  public signerTitle = signal<string>('');
  public authorizationDate = signal<string>('');

  constructor() {
    // Listen for real-time Go events emitted via runtime.EventsEmit
    if (window.runtime) {
      window.runtime.EventsOn('asset:updated', (payload: any) => {
        console.log('Received asset update:', payload);
        this.refreshAssets();
      });

      window.runtime.EventsOn('finding:new', (payload: any) => {
        console.log('Received new finding:', payload);
        this.refreshFindings(payload.assetId);
      });
      
      window.runtime.EventsOn('scan:complete', () => {
        console.log('Scan completely finished natively.');
        this.refreshSecretFindings();
        this.refreshEmailPostures();
        this.isScanning.set(false);
        this.scanStatusMessage.set('Scan Complete! Findings have been ingested.');
        setTimeout(() => this.scanStatusMessage.set(''), 8000);
      });
    }
  }

  // Wrappers for Go exported methods in App struct
  public async loadSettings(): Promise<void> {
    if (window.go && window.go.main && window.go.main.App) {
      const scopeData = await window.go.main.App.GetSetting('scope_settings');
      if (scopeData) {
        try {
          const s = JSON.parse(scopeData);
          this.seedDomainsList.set(s.seedDomainsList || []);
          this.seedCidrsList.set(s.seedCidrsList || []);
          this.seedReposList.set(s.seedReposList || []);
          this.isAuthorized.set(s.isAuthorized || false);
          this.signerName.set(s.signerName || '');
          this.signerTitle.set(s.signerTitle || '');
          this.authorizationDate.set(s.authorizationDate || '');
        } catch (e) {
          console.error('Failed to parse scope settings:', e);
        }
      }
    }
  }

  public async saveSettings(): Promise<void> {
    if (window.go && window.go.main && window.go.main.App) {
      const payload = JSON.stringify({
        seedDomainsList: this.seedDomainsList(),
        seedCidrsList: this.seedCidrsList(),
        seedReposList: this.seedReposList(),
        isAuthorized: this.isAuthorized(),
        signerName: this.signerName(),
        signerTitle: this.signerTitle(),
        authorizationDate: this.authorizationDate()
      });
      await window.go.main.App.SaveSetting('scope_settings', payload);
    }
  }

  public async refreshAssets(status: string = ''): Promise<void> {
    if (window.go && window.go.main && window.go.main.App) {
      const data = await window.go.main.App.GetAssets(status);
      this.assets.set(data || []);
    }
  }

  public async refreshFindings(assetId: string): Promise<void> {
    if (window.go && window.go.main && window.go.main.App) {
      const data = await window.go.main.App.GetFindings(assetId);
      this.findings.set(data || []);
    }
  }

  public async triggerScan(domain: string, repoUrl: string): Promise<void> {
    if (window.go && window.go.main && window.go.main.App) {
      await window.go.main.App.TriggerScan(domain, repoUrl);
    }
  }

  public async refreshSecretFindings(repoUrl: string = ''): Promise<void> {
    if (window.go && window.go.main && window.go.main.App && window.go.main.App.GetSecretFindings) {
      const data = await window.go.main.App.GetSecretFindings(repoUrl);
      const mapped = (data || []).map((s: any) => ({
        ...s,
        _id: s.id,
        provider: s.secretType,
        lineNumber: s.startLine,
        priority: 'high',
        status: 'open',
        commitSha: 'unknown'
      }));
      this.secretFindings.set(mapped);
    }
  }

  public async refreshEmailPostures(): Promise<void> {
    if (window.go && window.go.main && window.go.main.App && window.go.main.App.GetEmailPostures) {
      const data = await window.go.main.App.GetEmailPostures();
      this.emailPostures.set(data || []);
    }
  }
}
